name: Assistant Sync

permissions:
  contents: write

on:
  workflow_dispatch: {}         # lets you click "Run workflow"
  push:
    paths:
      - "ai/**"
      - "ops/sync_assistants.py"
      - ".github/workflows/assistant-sync.yml"
  schedule:
    - cron: "0 9 * * *"        # optional: daily sync at 09:00 UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml openai

      - name: Sync Assistant
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Provide either one; script reads either name
          ASSISTANT_ID_ORCH: ${{ secrets.ASSISTANT_ID_ORCH }}
          ASST_ORCHESTRATOR_ID: ${{ secrets.ASST_ORCHESTRATOR_ID }}
          OPENAI_MODEL: gpt-4o-mini
        run: |
          python ops/sync_assistants.py

      - name: Commit sync info (optional)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ai/assistant_sync_info.json || true
          git commit -m "chore: record assistant sync info" || echo "no changes"
          git push || true
