name: Auto PR Agent

# ✅ permissions required to write commits/PRs and comment on issues
permissions:
  contents: write
  pull-requests: write
  issues: write

on:
  # Manual run button (useful for testing)
  workflow_dispatch: {}
  # Fire on Issue create/edit/label events
  issues:
    types: [opened, edited, labeled]

concurrency:
  # Avoid duplicate runs per issue
  group: auto-pr-${{ github.event.issue.number || 'manual' }}
  cancel-in-progress: true

jobs:
  open-pr:
    # ✅ Run if the issue HAS the 'build' label.
    # - For "labeled" events, use event.label.name
    # - For opened/edited, search the labels array
    if: >
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'issues' && (
        (github.event.action == 'labeled' && github.event.label.name == 'build') ||
        (github.event.action != 'labeled' && contains(toJson(github.event.issue.labels), 'build')
      )))

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      # 🧠 This is the "code generator" placeholder.
      # For now we just create/update a small file so there's always something to commit.
      # (Later, we can replace this with a real generator that builds the UI files.)
      - name: Generate PR content from issue
        run: |
          mkdir -p .autopr
          echo "Auto PR from issue #${{ github.event.issue.number || 'manual' }}" > .autopr/ISSUE_${{ github.event.issue.number || 'manual' }}.md
          echo "" >> .autopr/ISSUE_${{ github.event.issue.number || 'manual' }}.md
          echo "Title: ${{ github.event.issue.title || 'manual' }}" >> .autopr/ISSUE_${{ github.event.issue.number || 'manual' }}.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "feat: auto PR from issue #${{ github.event.issue.number || 'manual' }}"
          branch: auto/issue-${{ github.event.issue.number || 'manual' }}
          title: "Auto PR: ${{ github.event.issue.title || 'Manual run' }}"
          body: |
            Auto-generated from issue #${{ github.event.issue.number || 'manual' }}.

            _Replace this stub step with your real generator to add pages/components._
          labels: |
            build
          add-paths: |
            .autopr/**
