# /.github/workflows/one-button-build.yml
name: One-Button Build

on:
  workflow_dispatch: {}
  push:
    paths:
      - "ai/tabs/*.yaml"
      - "spec/**"
      - "ops/generate_from_spec.py"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Generate from spec / fix YAML intents / build index
        run: |
          python ops/generate_from_spec.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: spec auto-sync (intents/index)"
          branch: auto/spec-sync
          title: "Spec Auto-Sync: intents/index"
          body: |
            This PR was created by One-Button Build:
            - Ensured every tab YAML has a top-level `intent:`
            - Regenerated `ai/index.json`
          labels: |
            build
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
